UserGuide: small edit
CS2103AUG2017-W09-B1/main pull request #59
Opened 2017-10-10 16:32 UTC by CindyTsai1

2017-10-10 17:00 UTC, nbriannl commented on docs/UserGuide.adoc
> +Format: `add n/NAME [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [b/BIRTHDAY] [tt/TIMETABLE_URL] [t/TAG] ...` +
alot of people conflicting over this line. putting your PR on hold

2017-10-10 17:10 UTC, April0616 submitted a review, later dismissed
Correct

2017-10-11 00:46 UTC, CindyTsai1 commented on docs/UserGuide.adoc
> +Format: `add n/NAME [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [b/BIRTHDAY] [tt/TIMETABLE_URL] [t/TAG] ...` +
I believe we cannot expect all contacts that we add to have phone numbers
we might only have their emails as well
so it's more logical to keep all fields optional while the name is a compulsory field

2017-10-11 00:47 UTC, CindyTsai1 commented on docs/UserGuide.adoc
> +Format: `add n/NAME [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [b/BIRTHDAY] [tt/TIMETABLE_URL] [t/TAG] ...` +
If we all agree on this, the addCommand.java will have to be altered

2017-10-11 02:47 UTC, zacharytang commented on docs/AboutUs.adoc
> +image::damithc.jpg[width="150", align="left"]
Something wrong here? Why is the file name reverted back to the dummy file

2017-10-11 04:19 UTC, nbriannl requested changes
change line 14 in AboutUs.adoc back to yuting.jpg

2017-10-11 05:14 UTC, nbriannl approved these changes

2017-10-11 05:17 UTC, merged